// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConsentFriend(arg1, arg2, arg3) {
  return window['go']['api']['MyApp']['ConsentFriend'](arg1, arg2, arg3);
}

export function CrateRoomReceive(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['api']['MyApp']['CrateRoomReceive'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateRoom(arg1) {
  return window['go']['api']['MyApp']['CreateRoom'](arg1);
}

export function FriendList(arg1) {
  return window['go']['api']['MyApp']['FriendList'](arg1);
}

export function GetApplicationRecord(arg1) {
  return window['go']['api']['MyApp']['GetApplicationRecord'](arg1);
}

export function GetConsentList(arg1) {
  return window['go']['api']['MyApp']['GetConsentList'](arg1);
}

export function GetIsSpeakUserInfo(arg1) {
  return window['go']['api']['MyApp']['GetIsSpeakUserInfo'](arg1);
}

export function HandleAddFriendRequest(arg1, arg2, arg3) {
  return window['go']['api']['MyApp']['HandleAddFriendRequest'](arg1, arg2, arg3);
}

export function IsSpeak(arg1, arg2) {
  return window['go']['api']['MyApp']['IsSpeak'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['api']['MyApp']['Login'](arg1, arg2);
}

export function MessageList(arg1) {
  return window['go']['api']['MyApp']['MessageList'](arg1);
}

export function QueryRoom(arg1) {
  return window['go']['api']['MyApp']['QueryRoom'](arg1);
}

export function Receive(arg1, arg2, arg3, arg4) {
  return window['go']['api']['MyApp']['Receive'](arg1, arg2, arg3, arg4);
}

export function RegisterFunc(arg1, arg2) {
  return window['go']['api']['MyApp']['RegisterFunc'](arg1, arg2);
}

export function SearchUser(arg1, arg2) {
  return window['go']['api']['MyApp']['SearchUser'](arg1, arg2);
}

export function StartHTTPServer() {
  return window['go']['api']['MyApp']['StartHTTPServer']();
}
